name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install dependencies
      run: sudo apt install --fix-missing lib{asound2,x11,xext,xcursor,xinerama,xi,xrandr,xss,xxf86vm,sdl2,sdl2-ttf}-dev

    - name: Test
      run: go test -v ./...
